In [1]:
from model import *
train_grid_conv = [
# Convolutional layers
[[32, 64, 64], [32, 64, 0], [32, 0, 0], [10, 20, 20], [10,20,0]],
#Dense layers
[0, 10, 20, 64],
# Epochs
[5,10, 15, 20]]
mini_train_grid_conv = [
# Convolutional layers
[[32, 64, 64]],
#Dense layers
[64],
# Epochs
[5,10]]


train_images,train_labels,test_images,test_labels = ConvModel.get_data(DATA_PATH)
processed_train_images, processed_train_labels, processed_test_images, processed_test_labels = ConvModel.get_data(PREPROCESSED_DATA_PATH)


2024-02-05 08:14:42.521838: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2024-02-05 08:14:42.521862: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2024-02-05 08:14:42.521865: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2024-02-05 08:14:42.522291: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-02-05 08:14:42.522663: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [2]:
tf.one_hot(test_labels, 5)

<tf.Tensor: shape=(17, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)>

In [3]:
tf.one_hot(train_labels, 5)

<tf.Tensor: shape=(135, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0.